name: pheasant_build
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.7
  pheasant_temp: ^1.0.0
  pheasant_meta: ^1.0.0
  # path: ^1.8.0

dependency_overrides:
  pheasant_temp:
    path: ../pheasant_temp
  pheasant_meta:
    path: ../pheasant_meta

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
